# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    # configure filters
    task.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { flat: 'exact' } ]
        tags: ['api_platform.filter']
